#ifndef __MYUN2_GITHUB_COM__CORNELIUS__HTML__TAGS_HPP__
#define __MYUN2_GITHUB_COM__CORNELIUS__HTML__TAGS_HPP__

namespace myun2
{
	namespace cornelius
	{
		namespace html
		{
			DECL_CORNELIUS_HTML_TAG2(body_, "body");
			DECL_CORNELIUS_HTML_TAG(a);
			DECL_CORNELIUS_HTML_TAG(h1);
			DECL_CORNELIUS_HTML_TAG(h2);
			DECL_CORNELIUS_HTML_TAG(h3);
			DECL_CORNELIUS_HTML_TAG(h4);
			DECL_CORNELIUS_HTML_TAG(h5);
			DECL_CORNELIUS_HTML_TAG(h6);
		}
	}
}

#endif//__MYUN2_GITHUB_COM__CORNELIUS__HTML__TAGS_HPP__
